# **Model Building And Intrepretation**

### **Required Library**

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor
import pickle
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

### **Data Collection**

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/GUVI FINAL PROJRCT/RFS_Cleaned_Dataset.csv')

In [ ]:
df

,Store,Dept,IsHoliday,Temperature,Fuel_Price,Day,Month,Year,Type,Size,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Weekly_Sales
0,1,1,0,42.31,2.572,5,2,2010,1,151315,7422.4664,6443.322,145.5875,16721.9869,4489.6821,211.096358,8.10600,24924.5000
1,1,2,0,42.31,2.572,5,2,2010,1,151315,7422.4664,6443.322,145.5875,16721.9869,4489.6821,211.096358,8.10600,50605.2700
2,1,3,0,42.31,2.572,5,2,2010,1,151315,7422.4664,6443.322,145.5875,16721.9869,4489.6821,211.096358,8.10600,13740.1200
3,1,4,0,42.31,2.572,5,2,2010,1,151315,7422.4664,6443.322,145.5875,16721.9869,4489.6821,211.096358,8.10600,39954.0400
4,1,5,0,42.31,2.572,5,2,2010,1,151315,7422.4664,6443.322,145.5875,16721.9869,4489.6821,211.096358,8.10600,32229.3800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551474,45,94,0,76.06,3.804,26,7,2013,2,118221,212.0200,851.730,2.0600,10.8800,1864.5700,193.267465,8.67499,4392.5763
551475,45,95,0,76.06,3.804,26,7,2013,2,118221,212.0200,851.730,2.0600,10.8800,1864.5700,193.267465,8.67499,56064.7318
551476,45,96,0,76.06,3.804,26,7,2013,2,118221,212.0200,851.730,2.0600,10.8800,1864.5700,193.267465,8.67499,1094.3121
551477,45,97,0,76.06,3.804,26,7,2013,2,118221,212.0200,851.730,2.0600,10.8800,1864.5700,193.267465,8.67499,6337.4919
551478,45,98,0,76.06,3.804,26,7,2013,2,118221,212.0200,851.730,2.0600,10.8800,1864.5700,193.267465,8.67499,749.7942

## **Predictor vs Response Variable**

In [ ]:
x = df.drop('Weekly_Sales',axis=1)

y = df['Weekly_Sales']

In [ ]:
x.columns

Index(['Store', 'Dept', 'IsHoliday', 'Temperature', 'Fuel_Price', 'Day',
       'Month', 'Year', 'Type', 'Size', 'MarkDown1', 'MarkDown2', 'MarkDown3',
       'MarkDown4', 'MarkDown5', 'CPI', 'Unemployment'],
      dtype='object')

## **Model Selection**

In [ ]:
def model_regression(xtrain,xtest,ytrain,ytest,algorithm):


  for i in algorithm:

    model = i().fit(xtrain,ytrain)


    # predict for train and test accuracy

    y_train_pred = model.predict(xtrain)


    y_test_pred  = model.predict(xtest)

    # R2 score

    r2_training = r2_score(ytrain,y_train_pred)

    r2_testing = r2_score(ytest,y_test_pred)

    # MAE Score
    mae_testing = mean_absolute_error(ytest,y_test_pred)

    # MSE Score
    mse_testing = mean_squared_error(ytest,y_test_pred)

    # RMSE SCore
    rmse_testing = np.sqrt(mean_squared_error(ytest,y_test_pred))

    data = {'Algorithm':i.__name__, 'Training R2 Score':r2_training,'Testing R2 Score':r2_testing,'MAE':mae_testing,'MSE':mse_testing,'RMSE':rmse_testing}


    print(data)

**`Split Data`**

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2)

In [ ]:
model_regression(xtrain,xtest,ytrain,ytest,[RandomForestRegressor,DecisionTreeRegressor,ExtraTreesRegressor,AdaBoostRegressor,XGBRegressor,GradientBoostingRegressor])

{'Algorithm': 'RandomForestRegressor', 'Training R2 Score': 0.9973151500811724, 'Testing R2 Score': 0.9769857610476683, 'MAE': 1193.6342204833313, 'MSE': 11748340.24912464, 'RMSE': 3427.5851921031285}
{'Algorithm': 'DecisionTreeRegressor', 'Training R2 Score': 1.0, 'Testing R2 Score': 0.9574968155590637, 'MAE': 1683.0666671756007, 'MSE': 21697083.85828809, 'RMSE': 4658.012865835397}
{'Algorithm': 'ExtraTreesRegressor', 'Training R2 Score': 0.9999999999999999, 'Testing R2 Score': 0.9785393391484648, 'MAE': 1175.7644674524236, 'MSE': 10955267.570529884, 'RMSE': 3309.874252978485}
{'Algorithm': 'AdaBoostRegressor', 'Training R2 Score': -0.3158334500689537, 'Testing R2 Score': -0.326493914130104, 'MAE': 21883.443092959867, 'MSE': 677150431.6902347, 'RMSE': 26022.114281707294}
{'Algorithm': 'XGBRegressor', 'Training R2 Score': 0.9522167106503114, 'Testing R2 Score': 0.9441222964487436, 'MAE': 2947.4891156363174, 'MSE': 28524526.707991447, 'RMSE': 5340.8357686781055}
{'Algorithm': 'GradientBoostingRegressor', 'Training R2 Score': 0.7457809897452086, 'Testing R2 Score': 0.7393798094800673, 'MAE': 6964.474053488104, 'MSE': 133041752.12405415, 'RMSE': 11534.372636778047}